name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        java: [16-jdk]
    runs-on: ubuntu-20.04
    container:
      image: openjdk:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - run: |
          curl https://maven.fabricmc.net/net/java/jdk/openjdk-17-ea%2B24_linux-x64_bin.tar.gz --output java.tar.gz
          tar -xf java.tar.gz
      - run: ./gradlew build javadocJar checkMappings --stacktrace -Porg.gradle.java.installations.auto-download=false -Porg.gradle.java.installations.paths=$(pwd)/jdk-17
      - name: Build artifacts
        if: ${{ matrix.java == '16-jdk' }}
        continue-on-error: true
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
